### ISSUE TITLE
Uninitialized Constant Apipie (NameError) in Rails 4.0

### ISSUE THREAD

**Issue by xchang** [Apipie/apipie-rails#173]
I want to use it with my Rails 4 app, but got **uninitialized constant Apipie (NameError)**
right after installation. 

I followed the guide  by adding apipie to gemfile and run

```
bundle install
rails g apipie:install
```

Everything is fine until I try to start the app by running:
`rails s`

following is the log:

```
localhost:ray-repo xchang$ rails s
=> Booting WEBrick
=> Rails 4.0.0 application starting in development on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Exiting
/Users/xchang/workspace/config/initializers/apipie.rb:1:in `<top (required)>': uninitialized constant Apipie (NameError)
  from /Users/xchang/.rvm/gems/ruby-2.0.0-p247@ray/gems/railties-4.0.0/lib/rails/engine.rb:609:in `block (2 levels) in <class:Engine>'
  from /Users/xchang/.rvm/gems/ruby-2.0.0-p247@ray/gems/railties-4.0.0/lib/rails/engine.rb:608:in `each'
  from /Users/xchang/.rvm/gems/ruby-2.0.0-p247@ray/gems/railties-4.0.0/lib/rails/engine.rb:608:in `block in <class:Engine>'
  from /Users/xchang/.rvm/gems/ruby-2.0.0-p247@ray/gems/railties-4.0.0/lib/rails/initializable.rb:30:in `instance_exec'
  from /Users/xchang/.rvm/gems/ruby-2.0.0-p247@ray/gems/railties-4.0.0/lib/rails/initializable.rb:30:in `run'
  from /Users/xchang/.rvm/gems/ruby-2.0.0-p247@ray/gems/railties-4.0.0/lib/rails/initializable.rb:55:in `block in run_initializers'
  from /Users/xchang/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/tsort.rb:150:in `block in tsort_each'
  from /Users/xchang/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/tsort.rb:183:in `block (2 levels) in each_strongly_connected_component'
  from /Users/xchang/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/tsort.rb:210:in `block (2 levels) in each_strongly_connected_component_from'
  from /Users/xchang/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/tsort.rb:219:in `each_strongly_connected_component_from'
  from /Users/xchang/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/tsort.rb:209:in `block in each_strongly_connected_component_from'
  from /Users/xchang/.rvm/gems/ruby-2.0.0-p247@ray/gems/railties-4.0.0/lib/rails/initializable.rb:44:in `each'
  from /Users/xchang/.rvm/gems/ruby-2.0.0-p247@ray/gems/railties-4.0.0/lib/rails/initializable.rb:44:in `tsort_each_child'
  from /Users/xchang/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/tsort.rb:203:in `each_strongly_connected_component_from'
  from /Users/xchang/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/tsort.rb:182:in `block in each_strongly_connected_component'
  from /Users/xchang/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/tsort.rb:180:in `each'
  from /Users/xchang/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/tsort.rb:180:in `each_strongly_connected_component'
  from /Users/xchang/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/tsort.rb:148:in `tsort_each'
  from /Users/xchang/.rvm/gems/ruby-2.0.0-p247@ray/gems/railties-4.0.0/lib/rails/initializable.rb:54:in `run_initializers'
  from /Users/xchang/.rvm/gems/ruby-2.0.0-p247@ray/gems/railties-4.0.0/lib/rails/application.rb:215:in `initialize!'
  from /Users/xchang/.rvm/gems/ruby-2.0.0-p247@ray/gems/railties-4.0.0/lib/rails/railtie/configurable.rb:30:in `method_missing'
  from /Users/xchang/workspace/config/environment.rb:5:in `<top (required)>'
  from /Users/xchang/workspace/config.ru:3:in `block in <main>'
  from /Users/xchang/.rvm/gems/ruby-2.0.0-p247@ray/gems/rack-1.5.2/lib/rack/builder.rb:55:in `instance_eval'
  from /Users/xchang/.rvm/gems/ruby-2.0.0-p247@ray/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'
  from /Users/xchang/workspace/config.ru:in `new'
  from /Users/xchang/workspace/config.ru:in `<main>'
  from /Users/xchang/.rvm/gems/ruby-2.0.0-p247@ray/gems/rack-1.5.2/lib/rack/builder.rb:49:in `eval'
  from /Users/xchang/.rvm/gems/ruby-2.0.0-p247@ray/gems/rack-1.5.2/lib/rack/builder.rb:49:in `new_from_string'
  from /Users/xchang/.rvm/gems/ruby-2.0.0-p247@ray/gems/rack-1.5.2/lib/rack/builder.rb:40:in `parse_file'
  from /Users/xchang/.rvm/gems/ruby-2.0.0-p247@ray/gems/rack-1.5.2/lib/rack/server.rb:277:in `build_app_and_options_from_config'
  from /Users/xchang/.rvm/gems/ruby-2.0.0-p247@ray/gems/rack-1.5.2/lib/rack/server.rb:199:in `app'
  from /Users/xchang/.rvm/gems/ruby-2.0.0-p247@ray/gems/railties-4.0.0/lib/rails/commands/server.rb:48:in `app'
  from /Users/xchang/.rvm/gems/ruby-2.0.0-p247@ray/gems/rack-1.5.2/lib/rack/server.rb:314:in `wrapped_app'
  from /Users/xchang/.rvm/gems/ruby-2.0.0-p247@ray/gems/railties-4.0.0/lib/rails/commands/server.rb:75:in `start'
  from /Users/xchang/.rvm/gems/ruby-2.0.0-p247@ray/gems/railties-4.0.0/lib/rails/commands.rb:78:in `block in <top (required)>'
  from /Users/xchang/.rvm/gems/ruby-2.0.0-p247@ray/gems/railties-4.0.0/lib/rails/commands.rb:73:in `tap'
  from /Users/xchang/.rvm/gems/ruby-2.0.0-p247@ray/gems/railties-4.0.0/lib/rails/commands.rb:73:in `<top (required)>'
  from bin/rails:4:in `require'
  from bin/rails:4:in `<main>'
```

**Comment by jjm340** [comment]
+1

**Comment by TsaiKoga** [comment]
+1

**Comment by TsaiKoga** [comment]
Oh, my mistake. In Gemfile,
I first put it in group:
```ruby
group :doc do
  gem 'apipie-rails'
end
```
and I changed it outside, and it works
```ruby
gem 'apipie-rails'
```

**Comment by iNecas** [comment]
Thanks for sharing you experience and resolution to this issue. Closing unless somebody finds another reproducer that could be addressed in apipie code base
