### ISSUE TITLE
Unhelpful error message for newbies

### ISSUE THREAD

**Issue by AlekSi** [Apipie/apipie-rails#193]
Note: edited.

Initial setup is not very easy for newbies. For example, I created new Rails 4 app, scaffolded post and added apipie-rails 0.0.24: https://github.com/AlekSi/apipie-test

```
$ bin/rake --trace apipie:static
** Invoke apipie:static (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute apipie:static
rake aborted!
undefined method `[]' for nil:NilClass
/usr/local/lib/ruby/gems/2.0.0/gems/apipie-rails-0.0.24/lib/tasks/apipie.rake:85:in `generate_one_page'
/usr/local/lib/ruby/gems/2.0.0/gems/apipie-rails-0.0.24/lib/tasks/apipie.rake:28:in `block (3 levels) in <top (required)>'
/usr/local/lib/ruby/gems/2.0.0/gems/apipie-rails-0.0.24/lib/tasks/apipie.rake:133:in `with_loaded_documentation'
/usr/local/lib/ruby/gems/2.0.0/gems/apipie-rails-0.0.24/lib/tasks/apipie.rake:20:in `block (2 levels) in <top (required)>'
/usr/local/Cellar/ruby20/2.0.0-p353/lib/ruby/gems/2.0.0/gems/rake-10.1.1/lib/rake/task.rb:236:in `call'
/usr/local/Cellar/ruby20/2.0.0-p353/lib/ruby/gems/2.0.0/gems/rake-10.1.1/lib/rake/task.rb:236:in `block in execute'
/usr/local/Cellar/ruby20/2.0.0-p353/lib/ruby/gems/2.0.0/gems/rake-10.1.1/lib/rake/task.rb:231:in `each'
/usr/local/Cellar/ruby20/2.0.0-p353/lib/ruby/gems/2.0.0/gems/rake-10.1.1/lib/rake/task.rb:231:in `execute'
/usr/local/Cellar/ruby20/2.0.0-p353/lib/ruby/gems/2.0.0/gems/rake-10.1.1/lib/rake/task.rb:175:in `block in invoke_with_call_chain'
/usr/local/Cellar/ruby20/2.0.0-p353/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/usr/local/Cellar/ruby20/2.0.0-p353/lib/ruby/gems/2.0.0/gems/rake-10.1.1/lib/rake/task.rb:168:in `invoke_with_call_chain'
/usr/local/Cellar/ruby20/2.0.0-p353/lib/ruby/gems/2.0.0/gems/rake-10.1.1/lib/rake/task.rb:161:in `invoke'
/usr/local/Cellar/ruby20/2.0.0-p353/lib/ruby/gems/2.0.0/gems/rake-10.1.1/lib/rake/application.rb:149:in `invoke_task'
/usr/local/Cellar/ruby20/2.0.0-p353/lib/ruby/gems/2.0.0/gems/rake-10.1.1/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/local/Cellar/ruby20/2.0.0-p353/lib/ruby/gems/2.0.0/gems/rake-10.1.1/lib/rake/application.rb:106:in `each'
/usr/local/Cellar/ruby20/2.0.0-p353/lib/ruby/gems/2.0.0/gems/rake-10.1.1/lib/rake/application.rb:106:in `block in top_level'
/usr/local/Cellar/ruby20/2.0.0-p353/lib/ruby/gems/2.0.0/gems/rake-10.1.1/lib/rake/application.rb:115:in `run_with_threads'
/usr/local/Cellar/ruby20/2.0.0-p353/lib/ruby/gems/2.0.0/gems/rake-10.1.1/lib/rake/application.rb:100:in `top_level'
/usr/local/Cellar/ruby20/2.0.0-p353/lib/ruby/gems/2.0.0/gems/rake-10.1.1/lib/rake/application.rb:78:in `block in run'
/usr/local/Cellar/ruby20/2.0.0-p353/lib/ruby/gems/2.0.0/gems/rake-10.1.1/lib/rake/application.rb:165:in `standard_exception_handling'
/usr/local/Cellar/ruby20/2.0.0-p353/lib/ruby/gems/2.0.0/gems/rake-10.1.1/lib/rake/application.rb:75:in `run'
bin/rake:4:in `<main>'
Tasks: TOP => apipie:static
```

That's due to absent documentation (no `api`, `param` and other DSL calls). It would be nice to check this case and provide helpful error message.

**Comment by christoph-buente** [comment]
It is end of 2015 and this bug still seems to exists. 

```ruby
bundle exec rake apipie:static[1.0]
```
results in this error message:
```
NoMethodError: undefined method `[]' for nil:NilClass
apipie-rails-0.3.4/lib/tasks/apipie.rake:30:in `block (4 levels) in <top (required)>'
```

In fact doc is nil
```ruby
doc = Apipie.to_json(args[:version], nil, nil, lang) #29
doc[:docs][:link_extension] = "#{lang_ext(lang)}.html" #30
```

Any chance that can be fixed?

**Comment by muhammet** [comment]
+1

**Comment by mada41** [comment]
+1

**Comment by samnissen** [comment]
This is still a problem:

```ruby
$ rake apipie:static[1] --trace
** Invoke apipie:static (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute apipie:static
rake aborted!
NoMethodError: undefined method `[]' for nil:NilClass
/path/.rvm/gems/ruby-2.4.1/gems/apipie-rails-0.5.8/lib/tasks/apipie.rake:30:in `block (4 levels) in <top (required)>'
/path/.rvm/gems/ruby-2.4.1/gems/apipie-rails-0.5.8/lib/tasks/apipie.rake:26:in `each'
/path/.rvm/gems/ruby-2.4.1/gems/apipie-rails-0.5.8/lib/tasks/apipie.rake:26:in `block (3 levels) in <top (required)>'
/path/.rvm/gems/ruby-2.4.1/gems/apipie-rails-0.5.8/lib/tasks/apipie.rake:286:in `with_loaded_documentation'
/path/.rvm/gems/ruby-2.4.1/gems/apipie-rails-0.5.8/lib/tasks/apipie.rake:20:in `block (2 levels) in <top (required)>'
/path/.rvm/gems/ruby-2.4.1/gems/rake-12.3.0/lib/rake/task.rb:251:in `block in execute'
/path/.rvm/gems/ruby-2.4.1/gems/rake-12.3.0/lib/rake/task.rb:251:in `each'
/path/.rvm/gems/ruby-2.4.1/gems/rake-12.3.0/lib/rake/task.rb:251:in `execute'
/path/.rvm/gems/ruby-2.4.1/gems/rake-12.3.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
/path/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/path/.rvm/gems/ruby-2.4.1/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
/path/.rvm/gems/ruby-2.4.1/gems/rake-12.3.0/lib/rake/task.rb:181:in `invoke'
/path/.rvm/gems/ruby-2.4.1/gems/rake-12.3.0/lib/rake/application.rb:160:in `invoke_task'
/path/.rvm/gems/ruby-2.4.1/gems/rake-12.3.0/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/path/.rvm/gems/ruby-2.4.1/gems/rake-12.3.0/lib/rake/application.rb:116:in `each'
/path/.rvm/gems/ruby-2.4.1/gems/rake-12.3.0/lib/rake/application.rb:116:in `block in top_level'
/path/.rvm/gems/ruby-2.4.1/gems/rake-12.3.0/lib/rake/application.rb:125:in `run_with_threads'
/path/.rvm/gems/ruby-2.4.1/gems/rake-12.3.0/lib/rake/application.rb:110:in `top_level'
/path/.rvm/gems/ruby-2.4.1/gems/rake-12.3.0/lib/rake/application.rb:83:in `block in run'
/path/.rvm/gems/ruby-2.4.1/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
/path/.rvm/gems/ruby-2.4.1/gems/rake-12.3.0/lib/rake/application.rb:80:in `run'
/path/.rvm/gems/ruby-2.4.1/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/path/.rvm/gems/ruby-2.4.1/bin/rake:23:in `load'
/path/.rvm/gems/ruby-2.4.1/bin/rake:23:in `<main>'
Tasks: TOP => apipie:static
```
