### ISSUE TITLE
Doc Generation crash

### ISSUE THREAD

**Issue by vmvijo** [Apipie/apipie-rails#368]
vmmac01:MYCO xyxy$ rake apipie:static --trace
DEPRECATION WARNING: Support for Rails < 3.2.13 will be dropped from Formtastic 3.0. (called from require at /xyx/.rvm/gems/ruby-2.0.0-p576@global/gems/bundler-1.7.3/lib/bundler/runtime.rb:76)
/xyx/.rvm/gems/ruby-2.0.0-p576/gems/tlsmail-0.0.1/lib/net/smtp.rb:806: warning: already initialized constant Net::SMTPSession
/xyx/.rvm/gems/ruby-2.0.0-p576/gems/tlsmail-0.0.1/lib/net/smtp.rb:806: warning: previous definition of SMTPSession was here
/xyx/.rvm/gems/ruby-2.0.0-p576/gems/tlsmail-0.0.1/lib/net/pop.rb:687: warning: already initialized constant Net::POP
/xyx/.rvm/gems/ruby-2.0.0-p576/gems/tlsmail-0.0.1/lib/net/pop.rb:687: warning: previous definition of POP was here
/xyx/.rvm/gems/ruby-2.0.0-p576/gems/tlsmail-0.0.1/lib/net/pop.rb:688: warning: already initialized constant Net::POPSession
/xyx/.rvm/gems/ruby-2.0.0-p576/gems/tlsmail-0.0.1/lib/net/pop.rb:688: warning: previous definition of POPSession was here
/xyx/.rvm/gems/ruby-2.0.0-p576/gems/tlsmail-0.0.1/lib/net/pop.rb:689: warning: already initialized constant Net::POP3Session
/xyx/.rvm/gems/ruby-2.0.0-p576/gems/tlsmail-0.0.1/lib/net/pop.rb:689: warning: previous definition of POP3Session was here
/xyx/.rvm/gems/ruby-2.0.0-p576/gems/tlsmail-0.0.1/lib/net/pop.rb:702: warning: already initialized constant Net::APOPSession
/xyx/.rvm/gems/ruby-2.0.0-p576/gems/tlsmail-0.0.1/lib/net/pop.rb:702: warning: previous definition of APOPSession was here
** Invoke apipie:static (first_time)
** Invoke environment (first_time)
** Execute environment
Loading SlaveMultiMaster /xyx/work/phase5/MYCO/config/sunspot.yml
Creating single master http://solr01:8080/solr
Creating slave http://solr01:8080/solr
** Execute apipie:static
rake aborted!
NoMethodError: undefined method `[]' for nil:NilClass
/xyx/.rvm/gems/ruby-2.0.0-p576/bundler/gems/apipie-rails-48ce90de6606/lib/tasks/apipie.rake:28:in `block (3 levels) in <top (required)>'
/xyx/.rvm/gems/ruby-2.0.0-p576/bundler/gems/apipie-rails-48ce90de6606/lib/tasks/apipie.rake:155:in `with_loaded_documentation'
/xyx/.rvm/gems/ruby-2.0.0-p576/bundler/gems/apipie-rails-48ce90de6606/lib/tasks/apipie.rake:20:in `block (2 levels) in <top (required)>'
/xyx/.rvm/gems/ruby-2.0.0-p576/gems/rake-10.3.2/lib/rake/task.rb:240:in `call'
/xyx/.rvm/gems/ruby-2.0.0-p576/gems/rake-10.3.2/lib/rake/task.rb:240:in `block in execute'
/xyx/.rvm/gems/ruby-2.0.0-p576/gems/rake-10.3.2/lib/rake/task.rb:235:in `each'
/xyx/.rvm/gems/ruby-2.0.0-p576/gems/rake-10.3.2/lib/rake/task.rb:235:in `execute'
/xyx/.rvm/gems/ruby-2.0.0-p576/gems/rake-10.3.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/xyx/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/xyx/.rvm/gems/ruby-2.0.0-p576/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/xyx/.rvm/gems/ruby-2.0.0-p576/gems/rake-10.3.2/lib/rake/task.rb:165:in `invoke'
/xyx/.rvm/gems/ruby-2.0.0-p576/gems/rake-10.3.2/lib/rake/application.rb:150:in `invoke_task'
/xyx/.rvm/gems/ruby-2.0.0-p576/gems/rake-10.3.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/xyx/.rvm/gems/ruby-2.0.0-p576/gems/rake-10.3.2/lib/rake/application.rb:106:in `each'
/xyx/.rvm/gems/ruby-2.0.0-p576/gems/rake-10.3.2/lib/rake/application.rb:106:in `block in top_level'
/xyx/.rvm/gems/ruby-2.0.0-p576/gems/rake-10.3.2/lib/rake/application.rb:115:in `run_with_threads'
/xyx/.rvm/gems/ruby-2.0.0-p576/gems/rake-10.3.2/lib/rake/application.rb:100:in `top_level'
/xyx/.rvm/gems/ruby-2.0.0-p576/gems/rake-10.3.2/lib/rake/application.rb:78:in `block in run'
/xyx/.rvm/gems/ruby-2.0.0-p576/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
/xyx/.rvm/gems/ruby-2.0.0-p576/gems/rake-10.3.2/lib/rake/application.rb:75:in `run'
/xyx/.rvm/gems/ruby-2.0.0-p576/gems/rake-10.3.2/bin/rake:33:in `<top (required)>'
/xyx/.rvm/gems/ruby-2.0.0-p576/bin/rake:23:in `load'
/xyx/.rvm/gems/ruby-2.0.0-p576/bin/rake:23:in `<main>'
/xyx/.rvm/gems/ruby-2.0.0-p576/bin/ruby_executable_hooks:15:in `eval'
/xyx/.rvm/gems/ruby-2.0.0-p576/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => apipie:static
vmmac01:MYCO xyxy$

**Comment by vmvijo** [comment]
This is my first time using apipie and
