### ISSUE TITLE
param_group inside block: undefined method `apipie_concern?' for nil:NilClass

### ISSUE THREAD

**Issue by olegantonyan** [Apipie/apipie-rails#371]
Define a param_group

```
def_param_group :photo_urls do
  param :url_full, String  
  param :url_thumb, String
end
```

Then use it

```
api! 'Get all reports'
param_group :photo_urls
def index
....
```

And this will work just fine.
But put it inside param do block

```
api! 'Get all reports'
param :photo do
  param_group :photo_urls
end
def index
....
```

And boom!

```
undefined method `apipie_concern?' for nil:NilClass

/home/oleg/.rbenv/versions/2.2.2/lib64/ruby/gems/2.2.0/bundler/gems/apipie-rails-becc75b5f026/lib/apipie/dsl_definition.rb:336:in `param_group'
/home/oleg/projects/10levels-rails/app/controllers/api/v2/reports_controller.rb:32:in `block (2 levels) in <class:ReportsController>'
/home/oleg/.rbenv/versions/2.2.2/lib64/ruby/gems/2.2.0/bundler/gems/apipie-rails-becc75b5f026/lib/apipie/validator.rb:285:in `instance_exec'
/home/oleg/.rbenv/versions/2.2.2/lib64/ruby/gems/2.2.0/bundler/gems/apipie-rails-becc75b5f026/lib/apipie/validator.rb:285:in `initialize'
/home/oleg/.rbenv/versions/2.2.2/lib64/ruby/gems/2.2.0/bundler/gems/apipie-rails-becc75b5f026/lib/apipie/validator.rb:278:in `new'
/home/oleg/.rbenv/versions/2.2.2/lib64/ruby/gems/2.2.0/bundler/gems/apipie-rails-becc75b5f026/lib/apipie/validator.rb:278:in `build'
/home/oleg/.rbenv/versions/2.2.2/lib64/ruby/gems/2.2.0/bundler/gems/apipie-rails-becc75b5f026/lib/apipie/validator.rb:24:in `block in find'
/home/oleg/.rbenv/versions/2.2.2/lib64/ruby/gems/2.2.0/bundler/gems/apipie-rails-becc75b5f026/lib/apipie/validator.rb:23:in `each'
/home/oleg/.rbenv/versions/2.2.2/lib64/ruby/gems/2.2.0/bundler/gems/apipie-rails-becc75b5f026/lib/apipie/validator.rb:23:in `find'
/home/oleg/.rbenv/versions/2.2.2/lib64/ruby/gems/2.2.0/bundler/gems/apipie-rails-becc75b5f026/lib/apipie/param_description.rb:67:in `initialize'
```

Config:

```
Apipie.configure do |config|
  config.app_name                = "10levels"
  config.api_base_url            = "/api"
  config.doc_base_url            = "/apidoc"
  # where is your API defined?
  config.api_controllers_matcher = "#{Rails.root}/app/controllers/api/**/*.rb"
  config.validate = false
  config.app_info = "10levels API"
  config.required_by_default = true
end
```

```
gem 'apipie-rails', github: 'Apipie/apipie-rails'
```

**Comment by nyamadori** [comment]
me too!

**Comment by simonhintersonnleitner** [comment]
me too!

**Comment by bublik** [comment]
+1

**Comment by wtfiwtz** [comment]
A workaround for this is to specify the `scope` directly as a 2nd parameter, where the scope is the module where your documentation is found, so that `Apipie` can find it correctly.

```ruby
if defined?(Apipie)
  module AuthorDoc
    extend Apipie::DSL::Concern

    param :set, Array, required: true, desc: 'Set of authors to create' do
        param_group :create_author, AuthorDoc
    end
  end
end
```

If you put the documentation directly in your controller, the it would be something like `AuthorsController` instead of `AuthorDoc`.

**Comment by mr-dxdy** [comment]
+1

**Comment by prateekkish** [comment]
+1
