### ISSUE TITLE
Error after executing rails g apipie:install

### ISSUE THREAD

**Issue by mesirendon** [Apipie/apipie-rails#538]
I've added the gem to my Gemfile and after `rails g apipie:install` I get this:

```
/home/mesi/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/apipie-rails-0.4.0/lib/apipie/extractor/recorder.rb:149:in `included': undefined method `alias_method_chain' for ActionController::TestCase::Behavior:Module (NoMethodError)
        from /home/mesi/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/apipie-rails-0.4.0/lib/apipie/extractor.rb:20:in `include'
        from /home/mesi/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/apipie-rails-0.4.0/lib/apipie/extractor.rb:20:in `block (2 levels) in <class:Railtie>'
        from /home/mesi/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/apipie-rails-0.4.0/lib/apipie/extractor.rb:19:in `instance_eval'
        from /home/mesi/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/apipie-rails-0.4.0/lib/apipie/extractor.rb:19:in `block in <class:Railtie>'
        from /home/mesi/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.1.0.rc1/lib/rails/initializable.rb:30:in `instance_exec'
        from /home/mesi/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.1.0.rc1/lib/rails/initializable.rb:30:in `run'
        from /home/mesi/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.1.0.rc1/lib/rails/initializable.rb:59:in `block in run_initializers'
        from /home/mesi/.rbenv/versions/2.4.0/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
        from /home/mesi/.rbenv/versions/2.4.0/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /home/mesi/.rbenv/versions/2.4.0/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /home/mesi/.rbenv/versions/2.4.0/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /home/mesi/.rbenv/versions/2.4.0/lib/ruby/2.4.0/tsort.rb:347:in `each'
        from /home/mesi/.rbenv/versions/2.4.0/lib/ruby/2.4.0/tsort.rb:347:in `call'
        from /home/mesi/.rbenv/versions/2.4.0/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
        from /home/mesi/.rbenv/versions/2.4.0/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
        from /home/mesi/.rbenv/versions/2.4.0/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
        from /home/mesi/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.1.0.rc1/lib/rails/initializable.rb:58:in `run_initializers'
        from /home/mesi/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.1.0.rc1/lib/rails/application.rb:353:in `initialize!'
        from /home/mesi/Documents/University/10/Ingeniería de Software 2/Project/shimizusuntou/config/environment.rb:5:in `<top (required)>'
        from /home/mesi/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/spring-2.0.1/lib/spring/application.rb:92:in `require'
        from /home/mesi/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/spring-2.0.1/lib/spring/application.rb:92:in `preload'
        from /home/mesi/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/spring-2.0.1/lib/spring/application.rb:143:in `serve'
        from /home/mesi/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/spring-2.0.1/lib/spring/application.rb:131:in `block in run'
        from /home/mesi/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/spring-2.0.1/lib/spring/application.rb:125:in `loop'
        from /home/mesi/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/spring-2.0.1/lib/spring/application.rb:125:in `run'
        from /home/mesi/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/spring-2.0.1/lib/spring/application/boot.rb:19:in `<top (required)>'
        from /home/mesi/.rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/mesi/.rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from -e:1:in `<main>'
```

**Comment by mesirendon** [comment]
I'm using `gem 'rails', '~> 5.1.0.rc1'`

**Comment by iNecas** [comment]
It seems like issue addressed in https://github.com/Apipie/apipie-rails/pull/530, 0.5.0 was just released, including the changes that should be necessary for this to work
