### ISSUE TITLE
Error when first setting up Apipie

### ISSUE THREAD

**Issue by bigmountainben** [Apipie/apipie-rails#612]
I followed the instructions to a T, and when loading the page `http://localhost:3000/apipie` or the `.json` variant, I get:

```
LoadError in Apipie::ApipiesController#index
Unable to autoload constant Concerns::Api::V1::Public::Errors, expected /Users/br/src/ud/server/app/controllers/concerns/api/v1/public/errors.rb to define it

def load_controller_from_file(controller_file)
      controller_class_name = controller_file.gsub(/\A.*\/app\/controllers\//,"").gsub(/\.\w*\Z/,"").camelize
      controller_class_name.constantize
    end

    def ignored?(controller, method = nil)

Rails.root: /Users/br/src/ud/server

Application Trace | Framework Trace | Full Trace
activesupport (5.0.6) lib/active_support/dependencies.rb:512:in `load_missing_constant'
activesupport (5.0.6) lib/active_support/dependencies.rb:203:in `const_missing'
activesupport (5.0.6) lib/active_support/inflector/methods.rb:270:in `const_get'
activesupport (5.0.6) lib/active_support/inflector/methods.rb:270:in `block in constantize'
activesupport (5.0.6) lib/active_support/inflector/methods.rb:266:in `each'
activesupport (5.0.6) lib/active_support/inflector/methods.rb:266:in `inject'
activesupport (5.0.6) lib/active_support/inflector/methods.rb:266:in `constantize'
activesupport (5.0.6) lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
apipie-rails (0.5.7) lib/apipie/application.rb:428:in `load_controller_from_file'
apipie-rails (0.5.7) lib/apipie/application.rb:317:in `block in reload_documentation'
apipie-rails (0.5.7) lib/apipie/application.rb:316:in `each'
apipie-rails (0.5.7) lib/apipie/application.rb:316:in `reload_documentation'
apipie-rails (0.5.7) lib/apipie/apipie_module.rb:23:in `method_missing'
apipie-rails (0.5.7) lib/apipie/application.rb:326:in `load_documentation'
apipie-rails (0.5.7) lib/apipie/apipie_module.rb:23:in `method_missing'
apipie-rails (0.5.7) app/controllers/apipie/apipies_controller.rb:37:in `block in index'
actionpack (5.0.6) lib/action_controller/metal/mime_responds.rb:195:in `respond_to'
apipie-rails (0.5.7) app/controllers/apipie/apipies_controller.rb:28:in `index'
actionpack (5.0.6) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
actionpack (5.0.6) lib/abstract_controller/base.rb:188:in `process_action'
actionpack (5.0.6) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.0.6) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (5.0.6) lib/active_support/callbacks.rb:126:in `call'
activesupport (5.0.6) lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
activesupport (5.0.6) lib/active_support/callbacks.rb:455:in `call'
```

**Comment by Petercopter** [comment]
@bigmountainben something in here should resolve it for you https://github.com/Apipie/apipie-rails/issues/347
