### ISSUE TITLE
LoadError: Unable to autoload constant Concerns::ModuleName when running static_swagger_json

### ISSUE THREAD

**Issue by belgoros** [Apipie/apipie-rails#651]
I have a module defined in `controllers/concerns`as follows:
```
#controllers/concerns/error_serializer.rb

module ErrorSerializer
  extend ActiveSupport::Concern
  extend Apipie::DSL::Concern  

  def self.serialize(object)
    errors = []
    object.errors.messages.map do |field, errors|
      errors.map do |error_message|
        {
          status: 422,
          title: 'Invalid attribute',
          source: { pointer: "/data/attributes/#{field}" },
          detail: error_message
        }
      end
    end.flatten
  end
end
```
When I run `rake apipie:static_swagger_json` I get th ebelow error:
```
rake aborted!
LoadError: Unable to autoload constant Concerns::ErrorSerializer, expected /Users/Serguei/projects/decastore/decastore-api/app/controllers/concerns/error_serializer.rb to define it
/Users/Serguei/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:503:in `load_missing_constant'
/Users/Serguei/.rvm/gems/ruby-2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:58:in `block in load_missing_constant'
/Users/Serguei/.rvm/gems/ruby-2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry'
/Users/Serguei/.rvm/gems/ruby-2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:57:in `load_missing_constant'
/Users/Serguei/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:193:in `const_missing'
/Users/Serguei/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/inflector/methods.rb:285:in `const_get'
/Users/Serguei/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/inflector/methods.rb:285:in `block in constantize'
/Users/Serguei/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/inflector/methods.rb:281:in `each'
/Users/Serguei/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/inflector/methods.rb:281:in `inject'
/Users/Serguei/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/inflector/methods.rb:281:in `constantize'
/Users/Serguei/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/core_ext/string/inflections.rb:68:in `constantize'
/Users/Serguei/.rvm/gems/ruby-2.5.0/gems/apipie-rails-0.5.14/lib/apipie/application.rb:438:in `load_controller_from_file'
/Users/Serguei/.rvm/gems/ruby-2.5.0/gems/apipie-rails-0.5.14/lib/apipie/application.rb:327:in `block in reload_documentation'
/Users/Serguei/.rvm/gems/ruby-2.5.0/gems/apipie-rails-0.5.14/lib/apipie/application.rb:326:in `each'
/Users/Serguei/.rvm/gems/ruby-2.5.0/gems/apipie-rails-0.5.14/lib/apipie/application.rb:326:in `reload_documentation'
/Users/Serguei/.rvm/gems/ruby-2.5.0/gems/apipie-rails-0.5.14/lib/apipie/apipie_module.rb:34:in `method_missing'
/Users/Serguei/.rvm/gems/ruby-2.5.0/gems/apipie-rails-0.5.14/lib/tasks/apipie.rake:285:in `with_loaded_documentation'
/Users/Serguei/.rvm/gems/ruby-2.5.0/gems/apipie-rails-0.5.14/lib/tasks/apipie.rake:56:in `block (2 levels) in <main>'
```
I just tried to see how it works for the only controller:
```
#controllers/v1/languages_controller.rb

module V1
  class LanguagesController < ApplicationController
    before_action :find_language, only: :show

    api!
    def index
      @languages = Language.all
      json_response @languages, :ok
    end

    api!
    def show
      json_response @language
    end

    private

    def find_language
      @language = Language.find(params[:id])
    end
  end
end
``` 
Used environment:
- macOS Mojave 10.14.1
- Ruby 2.5.0
- Rails 5.2.0 (api mode)
- apipie-rails',          '~> 0.5.14'

What am I missing ?

**Comment by Shelvak** [comment]
I have the same issue with *ALL* the controllers concerns... 
ruby 2.4
rails 5.1.6
apipie-rails (0.5.15)

**Comment by vadimeremeev** [comment]
Same issue 
ruby 2.6.0
rails 5.2.0
apipie-rails 0.5.6
